import type { Metadata } from "next";
import { org } from "@/lib/org";

function resolveSiteUrl(): string {
  const fromEnv = process.env.NEXT_PUBLIC_SITE_URL?.trim().replace(/\/$/, "");
  if (fromEnv) return fromEnv;
  if (process.env.NODE_ENV === "production") {
    throw new Error(
      "NEXT_PUBLIC_SITE_URL must be set for production builds (e.g. https://owuf.gov.et).",
    );
  }
  return "http://localhost:3000";
}

export const SITE_URL = resolveSiteUrl();

/** Dynamic OG image generated by app/opengraph-image.tsx */
export const DEFAULT_OG_IMAGE = `${SITE_URL}/opengraph-image`;

export const siteConfig = {
  name: org.name.en,
  shortName: org.shortName,
  description:
    "Official website of the Oromia Water Utilities Federation (OWUF). Explore services, projects, member utilities, news, and resources under Proclamation No. 228/2020 — Strategic Plan 2026–2030.",
  locale: "en_ET",
  locales: ["en", "om", "am"] as const,
  alternateLocales: ["om_ET", "am_ET"] as const,
  keywords: [
    "OWUF",
    "Oromia Water Utilities Federation",
    "Oromia water utilities",
    "Water Service Providers Oromia",
    "potable water Ethiopia",
    "sewage services Oromia",
    "Proclamation 228/2020",
    "non-revenue water",
    "utility capacity building",
    "SDG 6 Ethiopia",
    "OWEB",
    "MoWE",
    "Finfinnee",
    "Addis Ababa water",
    "Oromia sanitation",
  ],
};

type BuildMetadataInput = {
  title: string;
  description: string;
  path?: string;
  image?: string;
  type?: "website" | "article";
  noIndex?: boolean;
  publishedTime?: string;
  modifiedTime?: string;
  /** Override Open Graph locale string (e.g. en_ET) */
  locale?: string;
  /** Active site language for canonical + OG (en | om | am) */
  contentLocale?: "en" | "om" | "am";
};

export function absoluteUrl(path = "/") {
  if (!path.startsWith("/")) return `${SITE_URL}/${path}`;
  return `${SITE_URL}${path}`;
}

export function localizedPath(locale: string, path = "/") {
  const clean = path === "/" ? "" : path.startsWith("/") ? path : `/${path}`;
  return `/${locale}${clean}`;
}

export function buildMetadata({
  title,
  description,
  path = "/",
  image = DEFAULT_OG_IMAGE,
  type = "website",
  noIndex = false,
  publishedTime,
  modifiedTime,
  locale,
  contentLocale = "en",
}: BuildMetadataInput): Metadata {
  const active = contentLocale;
  const ogLocale =
    locale ||
    (active === "am" ? "am_ET" : active === "om" ? "om_ET" : "en_ET");
  const canonicalUrl = absoluteUrl(localizedPath(active, path));
  const defaultUrl = absoluteUrl(localizedPath("en", path));
  const languageUrls = Object.fromEntries(
    siteConfig.locales.map((loc) => [
      loc,
      absoluteUrl(localizedPath(loc, path)),
    ]),
  ) as Record<string, string>;

  const ogTitle = title.includes(org.shortName)
    ? title
    : `${title} | ${org.shortName}`;

  const alternateLocale = siteConfig.locales
    .filter((loc) => loc !== active)
    .map((loc) => (loc === "am" ? "am_ET" : loc === "om" ? "om_ET" : "en_ET"));

  return {
    title,
    description,
    keywords: siteConfig.keywords,
    authors: [{ name: org.name.en, url: SITE_URL }],
    creator: org.shortName,
    publisher: org.name.en,
    category: "Government",
    alternates: {
      canonical: canonicalUrl,
      languages: {
        ...languageUrls,
        "x-default": defaultUrl,
      },
      types: {
        "application/rss+xml": absoluteUrl("/feed.xml"),
      },
    },
    openGraph: {
      type,
      url: canonicalUrl,
      title: ogTitle,
      description,
      siteName: org.name.en,
      locale: ogLocale,
      alternateLocale,
      images: [
        {
          url: image,
          width: 1200,
          height: 630,
          alt: `${org.shortName} — ${org.name.en}`,
        },
      ],
      ...(publishedTime ? { publishedTime } : {}),
      ...(modifiedTime ? { modifiedTime } : {}),
    },
    twitter: {
      card: "summary_large_image",
      title: ogTitle,
      description,
      images: [image],
    },
    robots: noIndex
      ? { index: false, follow: false }
      : {
          index: true,
          follow: true,
          googleBot: {
            index: true,
            follow: true,
            "max-image-preview": "large",
            "max-snippet": -1,
            "max-video-preview": -1,
          },
        },
  };
}

export function organizationJsonLd() {
  const sameAs = [
    `https://${org.domain}`,
    ...Object.values(org.social).filter(
      (url) =>
        url &&
        !url.endsWith("facebook.com") &&
        !url.endsWith("linkedin.com") &&
        !url.endsWith("t.me"),
    ),
  ];

  return {
    "@context": "https://schema.org",
    "@type": "GovernmentOrganization",
    "@id": `${SITE_URL}/#organization`,
    name: org.name.en,
    legalName: org.legalName.en,
    alternateName: [org.shortName, org.name.om, org.name.am],
    url: absoluteUrl("/en"),
    logo: {
      "@type": "ImageObject",
      url: absoluteUrl(org.logoSvg ?? org.logo),
    },
    image: absoluteUrl("/brand/photos/hero.png"),
    email: org.email,
    ...(org.phone.filter((p) => p && !p.includes("000 0000")).length
      ? {
          telephone: org.phone.filter((p) => p && !p.includes("000 0000")),
        }
      : {}),
    taxID: org.tin,
    address: {
      "@type": "PostalAddress",
      streetAddress: org.address.en,
      addressLocality: "Finfinnee",
      addressRegion: "Oromia",
      addressCountry: "ET",
    },
    areaServed: {
      "@type": "AdministrativeArea",
      name: "Oromia Regional State, Ethiopia",
    },
    parentOrganization: org.supervisingBodies.map((name) => ({
      "@type": "GovernmentOrganization",
      name,
    })),
    sameAs,
    description: siteConfig.description,
    foundingDate: "2020",
    knowsAbout: [
      "Water supply",
      "Sanitation",
      "Utility capacity building",
      "Non-revenue water",
      "Sector advocacy",
    ],
    identifier: [
      { "@type": "PropertyValue", name: "TIN", value: org.tin },
      { "@type": "PropertyValue", name: "Proclamation", value: org.proclamation },
    ],
    contactPoint: [
      {
        "@type": "ContactPoint",
        contactType: "customer service",
        email: org.email,
        url: absoluteUrl("/en/contact"),
        availableLanguage: ["English", "Afaan Oromo", "Amharic"],
        areaServed: "ET-OR",
      },
    ],
  };
}

export function websiteJsonLd() {
  return {
    "@context": "https://schema.org",
    "@type": "WebSite",
    "@id": `${SITE_URL}/#website`,
    name: org.name.en,
    alternateName: org.shortName,
    url: absoluteUrl("/en"),
    inLanguage: ["en", "om", "am"],
    publisher: { "@id": `${SITE_URL}/#organization` },
    potentialAction: {
      "@type": "SearchAction",
      target: {
        "@type": "EntryPoint",
        urlTemplate: `${SITE_URL}/en/search?q={search_term_string}`,
      },
      "query-input": "required name=search_term_string",
    },
  };
}

export function breadcrumbJsonLd(
  items: Array<{ name: string; path: string }>,
) {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: items.map((item, index) => {
      const path = item.path.startsWith("/en") ||
        item.path.startsWith("/om") ||
        item.path.startsWith("/am")
        ? item.path
        : localizedPath("en", item.path);
      return {
        "@type": "ListItem",
        position: index + 1,
        name: item.name,
        item: absoluteUrl(path),
      };
    }),
  };
}

export function articleJsonLd(input: {
  title: string;
  description: string;
  path: string;
  datePublished?: string | null;
  dateModified?: string | null;
  image?: string | null;
}) {
  const path =
    input.path.startsWith("/en") ||
    input.path.startsWith("/om") ||
    input.path.startsWith("/am")
      ? input.path
      : localizedPath("en", input.path);

  return {
    "@context": "https://schema.org",
    "@type": "NewsArticle",
    headline: input.title,
    description: input.description,
    mainEntityOfPage: absoluteUrl(path),
    url: absoluteUrl(path),
    image: input.image ? [absoluteUrl(input.image)] : [DEFAULT_OG_IMAGE],
    datePublished: input.datePublished || undefined,
    dateModified: input.dateModified || input.datePublished || undefined,
    inLanguage: "en",
    author: {
      "@type": "Organization",
      name: org.name.en,
      url: absoluteUrl("/en"),
    },
    publisher: {
      "@type": "GovernmentOrganization",
      name: org.name.en,
      logo: {
        "@type": "ImageObject",
        url: absoluteUrl(org.logo),
      },
    },
  };
}

export function contactPageJsonLd() {
  return {
    "@context": "https://schema.org",
    "@type": "ContactPage",
    "@id": `${SITE_URL}/en/contact#webpage`,
    name: `Contact ${org.shortName}`,
    url: absoluteUrl("/en/contact"),
    isPartOf: { "@id": `${SITE_URL}/#website` },
    about: { "@id": `${SITE_URL}/#organization` },
    mainEntity: {
      "@type": "GovernmentOrganization",
      name: org.name.en,
      email: org.email,
      url: absoluteUrl("/en"),
      address: {
        "@type": "PostalAddress",
        streetAddress: org.address.en,
        addressLocality: "Finfinnee",
        addressRegion: "Oromia",
        addressCountry: "ET",
      },
    },
  };
}

export function eventJsonLd(input: {
  name: string;
  description: string;
  path: string;
  startDate: string;
  endDate?: string | null;
  location?: string | null;
}) {
  return {
    "@context": "https://schema.org",
    "@type": "Event",
    name: input.name,
    description: input.description,
    startDate: input.startDate,
    endDate: input.endDate || undefined,
    eventAttendanceMode: "https://schema.org/OfflineEventAttendanceMode",
    eventStatus: "https://schema.org/EventScheduled",
    url: absoluteUrl(localizedPath("en", input.path)),
    location: {
      "@type": "Place",
      name: input.location || "Oromia, Ethiopia",
      address: {
        "@type": "PostalAddress",
        addressRegion: "Oromia",
        addressCountry: "ET",
      },
    },
    organizer: {
      "@type": "GovernmentOrganization",
      name: org.name.en,
      url: absoluteUrl("/en"),
    },
  };
}

export function webPageJsonLd(input: {
  name: string;
  description: string;
  path: string;
}) {
  return {
    "@context": "https://schema.org",
    "@type": "WebPage",
    name: input.name,
    description: input.description,
    url: absoluteUrl(localizedPath("en", input.path)),
    isPartOf: { "@id": `${SITE_URL}/#website` },
    about: { "@id": `${SITE_URL}/#organization` },
    inLanguage: ["en", "om", "am"],
  };
}
